# EVN

In [3]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

# 행렬연산

## 데이터

In [ ]:
hidden = np.random.randint(-9, 10, (5, 4)) / 10
hidden

## element wise sum

In [ ]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden + arg

In [ ]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden + arg

In [ ]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden + arg

In [ ]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden + arg

In [ ]:
hidden + 1

In [ ]:
1 + hidden

## element wise multiplication

In [ ]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden * arg

In [ ]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden * arg

In [ ]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden * arg

In [ ]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden * arg

In [ ]:
hidden * 2

In [ ]:
2 * hidden

## matrix multiplication

In [22]:
arg = np.random.randint(-9, 10, (4, 5)) / 10
arg, np.matmul(hidden, arg)

(array([[ 0.2, -0.9, -0.2, -0.6, -0.7],
        [-0.7,  0.4,  0.8,  0.1, -0.1],
        [ 0.3,  0.8, -0.7, -0.7, -0.2],
        [ 0.6,  0.1, -0.4, -0.7,  0.3]]),
 array([[ 0.28,  0.84, -0.64,  0.15,  0.34],
        [-0.33, -0.63,  0.6 ,  0.27, -0.12],
        [-0.11,  0.31,  0.33, -0.23,  0.21],
        [ 0.01, -0.91, -0.22,  0.09, -0.68],
        [ 0.04,  0.27,  0.35,  0.6 ,  0.96]]))

In [23]:
val = np.zeros((hidden.shape[0], arg.shape[1]))
val

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
for row in range(hidden.shape[0]):
    row_v = hidden[row]
    for col in range(arg.shape[1]):
        col_v = arg[:, col]
        val[row][col] = np.dot(row_v, col_v)
val

array([[ 0.28,  0.84, -0.64,  0.15,  0.34],
       [-0.33, -0.63,  0.6 ,  0.27, -0.12],
       [-0.11,  0.31,  0.33, -0.23,  0.21],
       [ 0.01, -0.91, -0.22,  0.09, -0.68],
       [ 0.04,  0.27,  0.35,  0.6 ,  0.96]])